/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * configuraJerarquia.java
 *
 * Created on 31/03/2009, 05:59:21 PM
 */

package gestiontipocampo;

/**
 *
 * @author Ricardo
 */
public class configuraJerarquia extends javax.swing.JFrame {

    /** Creates new form configuraJerarquia */
    public configuraJerarquia() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkConfJerNombre = new javax.swing.JCheckBox();
        checkConfJerCategorias = new javax.swing.JCheckBox();
        checkConfJerNiveles = new javax.swing.JCheckBox();
        checkConfJerRelaciones = new javax.swing.JCheckBox();
        checkConfJerVersion = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(configuraJerarquia.class);
        checkConfJerNombre.setText(resourceMap.getString("checkConfJerNombre.text")); // NOI18N
        checkConfJerNombre.setName("checkConfJerNombre"); // NOI18N

        checkConfJerCategorias.setText(resourceMap.getString("checkConfJerCategorias.text")); // NOI18N
        checkConfJerCategorias.setName("checkConfJerCategorias"); // NOI18N
        checkConfJerCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkConfJerCategoriasActionPerformed(evt);
            }
        });

        checkConfJerNiveles.setText(resourceMap.getString("checkConfJerNiveles.text")); // NOI18N
        checkConfJerNiveles.setName("checkConfJerNiveles"); // NOI18N
        checkConfJerNiveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkConfJerNivelesActionPerformed(evt);
            }
        });

        checkConfJerRelaciones.setText(resourceMap.getString("checkConfJerRelaciones.text")); // NOI18N
        checkConfJerRelaciones.setName("checkConfJerRelaciones"); // NOI18N

        checkConfJerVersion.setText(resourceMap.getString("checkConfJerVersion.text")); // NOI18N
        checkConfJerVersion.setName("checkConfJerVersion"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(checkConfJerNombre)
                        .addGap(18, 18, 18)
                        .addComponent(checkConfJerCategorias)
                        .addGap(18, 18, 18)
                        .addComponent(checkConfJerNiveles))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(checkConfJerRelaciones)
                        .addGap(18, 18, 18)
                        .addComponent(checkConfJerVersion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkConfJerNombre)
                    .addComponent(checkConfJerCategorias)
                    .addComponent(checkConfJerNiveles))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkConfJerRelaciones)
                    .addComponent(checkConfJerVersion))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkConfJerCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkConfJerCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkConfJerCategoriasActionPerformed

    private void checkConfJerNivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkConfJerNivelesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkConfJerNivelesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new configuraJerarquia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkConfJerCategorias;
    private javax.swing.JCheckBox checkConfJerNiveles;
    private javax.swing.JCheckBox checkConfJerNombre;
    private javax.swing.JCheckBox checkConfJerRelaciones;
    private javax.swing.JCheckBox checkConfJerVersion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

}
