/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frameComandos.java
 *
 * Created on 24/05/2009, 10:19:33 PM
 */

package gestiontipocampo;

/**
 *
 * @author Ricardo
 */
public class frameComandos extends javax.swing.JFrame {

    /** Creates new form frameComandos */
    public frameComandos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        labelTipo = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox();
        labelDescripcion = new javax.swing.JLabel();
        fieldDescripcion = new javax.swing.JTextField();
        mainPane = new javax.swing.JLayeredPane();
        paneComandosFaciles = new javax.swing.JLayeredPane();
        labelSeleccionFormulario = new javax.swing.JLabel();
        comboSeleccionFormulario = new javax.swing.JComboBox();
        paneComandoMascara = new javax.swing.JLayeredPane();
        paneDivisionAccion = new javax.swing.JLayeredPane();
        paneAccionCombo = new javax.swing.JLayeredPane();
        comboAccion = new javax.swing.JComboBox();
        paneAccionField = new javax.swing.JLayeredPane();
        fieldAccion = new javax.swing.JTextField();
        labelCampoInicial = new javax.swing.JLabel();
        labelCondicionInicial = new javax.swing.JLabel();
        comboCampoInicial = new javax.swing.JComboBox();
        labelCondAccion = new javax.swing.JLabel();
        paneDivisionEfecto = new javax.swing.JLayeredPane();
        paneEfectoCombo = new javax.swing.JLayeredPane();
        comboEfecto = new javax.swing.JComboBox();
        paneEfectoField = new javax.swing.JLayeredPane();
        fieldEfecto = new javax.swing.JTextField();
        labelCampoFinal = new javax.swing.JLabel();
        labelCondicionInicial1 = new javax.swing.JLabel();
        comboCampoFinal = new javax.swing.JComboBox();
        labelCondFinal = new javax.swing.JLabel();
        botonAgregarAccion = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setLabelFor(fieldNombre);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameComandos.class);
        labelNombre.setText(resourceMap.getString("labelNombre.text")); // NOI18N
        labelNombre.setName("labelNombre"); // NOI18N
        getContentPane().add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        fieldNombre.setText(resourceMap.getString("fieldNombre.text")); // NOI18N
        fieldNombre.setName("fieldNombre"); // NOI18N
        getContentPane().add(fieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 250, -1));

        labelTipo.setLabelFor(comboTipo);
        labelTipo.setText(resourceMap.getString("labelTipo.text")); // NOI18N
        labelTipo.setName("labelTipo"); // NOI18N
        getContentPane().add(labelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTipo.setName("comboTipo"); // NOI18N
        getContentPane().add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        labelDescripcion.setLabelFor(fieldDescripcion);
        labelDescripcion.setText(resourceMap.getString("labelDescripcion.text")); // NOI18N
        labelDescripcion.setName("labelDescripcion"); // NOI18N
        getContentPane().add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        fieldDescripcion.setText(resourceMap.getString("fieldDescripcion.text")); // NOI18N
        fieldDescripcion.setName("fieldDescripcion"); // NOI18N
        getContentPane().add(fieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 180, 80));

        mainPane.setName("mainPane"); // NOI18N

        paneComandosFaciles.setName("paneComandosFaciles"); // NOI18N

        labelSeleccionFormulario.setLabelFor(comboSeleccionFormulario);
        labelSeleccionFormulario.setText(resourceMap.getString("labelSeleccionFormulario.text")); // NOI18N
        labelSeleccionFormulario.setName("labelSeleccionFormulario"); // NOI18N
        labelSeleccionFormulario.setBounds(10, 10, 180, 14);
        paneComandosFaciles.add(labelSeleccionFormulario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comboSeleccionFormulario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSeleccionFormulario.setName("comboSeleccionFormulario"); // NOI18N
        comboSeleccionFormulario.setBounds(10, 30, 180, 20);
        paneComandosFaciles.add(comboSeleccionFormulario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneComandoMascara.setName("paneComandoMascara"); // NOI18N

        paneDivisionAccion.setName("paneDivisionAccion"); // NOI18N

        paneAccionCombo.setName("paneAccionCombo"); // NOI18N

        comboAccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboAccion.setName("comboAccion"); // NOI18N
        comboAccion.setBounds(0, 0, 150, -1);
        paneAccionCombo.add(comboAccion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneAccionCombo.setBounds(0, 0, 150, 50);
        paneDivisionAccion.add(paneAccionCombo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneAccionField.setName("paneAccionField"); // NOI18N

        fieldAccion.setText(resourceMap.getString("fieldAccion.text")); // NOI18N
        fieldAccion.setName("fieldAccion"); // NOI18N
        fieldAccion.setBounds(0, 0, 150, -1);
        paneAccionField.add(fieldAccion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneAccionField.setBounds(0, 0, 160, 50);
        paneDivisionAccion.add(paneAccionField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneDivisionAccion.setBounds(180, 60, 170, 50);
        paneComandoMascara.add(paneDivisionAccion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        labelCampoInicial.setLabelFor(comboCampoInicial);
        labelCampoInicial.setText(resourceMap.getString("labelCampoInicial.text")); // NOI18N
        labelCampoInicial.setName("labelCampoInicial"); // NOI18N
        labelCampoInicial.setBounds(20, 40, 100, 14);
        paneComandoMascara.add(labelCampoInicial, javax.swing.JLayeredPane.DEFAULT_LAYER);

        labelCondicionInicial.setText(resourceMap.getString("labelCondicionInicial.text")); // NOI18N
        labelCondicionInicial.setName("labelCondicionInicial"); // NOI18N
        labelCondicionInicial.setBounds(80, 20, 80, 14);
        paneComandoMascara.add(labelCondicionInicial, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comboCampoInicial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCampoInicial.setName("comboCampoInicial"); // NOI18N
        comboCampoInicial.setBounds(20, 60, 130, 20);
        paneComandoMascara.add(comboCampoInicial, javax.swing.JLayeredPane.DEFAULT_LAYER);

        labelCondAccion.setLabelFor(paneDivisionAccion);
        labelCondAccion.setText(resourceMap.getString("labelCondAccion.text")); // NOI18N
        labelCondAccion.setName("labelCondAccion"); // NOI18N
        labelCondAccion.setBounds(180, 40, 100, 14);
        paneComandoMascara.add(labelCondAccion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneDivisionEfecto.setName("paneDivisionEfecto"); // NOI18N

        paneEfectoCombo.setName("paneEfectoCombo"); // NOI18N

        comboEfecto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEfecto.setName("comboEfecto"); // NOI18N
        comboEfecto.setBounds(0, 0, 150, -1);
        paneEfectoCombo.add(comboEfecto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneEfectoCombo.setBounds(0, 0, 150, 50);
        paneDivisionEfecto.add(paneEfectoCombo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneEfectoField.setName("paneEfectoField"); // NOI18N

        fieldEfecto.setName("fieldEfecto"); // NOI18N
        fieldEfecto.setBounds(0, 0, 150, -1);
        paneEfectoField.add(fieldEfecto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneEfectoField.setBounds(0, 0, 160, 50);
        paneDivisionEfecto.add(paneEfectoField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneDivisionEfecto.setBounds(500, 60, 170, 50);
        paneComandoMascara.add(paneDivisionEfecto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        labelCampoFinal.setLabelFor(comboCampoInicial);
        labelCampoFinal.setText(resourceMap.getString("labelCampoFinal.text")); // NOI18N
        labelCampoFinal.setName("labelCampoFinal"); // NOI18N
        labelCampoFinal.setBounds(340, 40, 100, 14);
        paneComandoMascara.add(labelCampoFinal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        labelCondicionInicial1.setText(resourceMap.getString("labelCondicionInicial1.text")); // NOI18N
        labelCondicionInicial1.setName("labelCondicionInicial1"); // NOI18N
        labelCondicionInicial1.setBounds(400, 20, 80, 14);
        paneComandoMascara.add(labelCondicionInicial1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comboCampoFinal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCampoFinal.setName("comboCampoFinal"); // NOI18N
        comboCampoFinal.setBounds(340, 60, 130, 20);
        paneComandoMascara.add(comboCampoFinal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        labelCondFinal.setLabelFor(paneDivisionAccion);
        labelCondFinal.setText(resourceMap.getString("labelCondFinal.text")); // NOI18N
        labelCondFinal.setName("labelCondFinal"); // NOI18N
        labelCondFinal.setBounds(500, 40, 100, 14);
        paneComandoMascara.add(labelCondFinal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        botonAgregarAccion.setText(resourceMap.getString("botonAgregarAccion.text")); // NOI18N
        botonAgregarAccion.setName("botonAgregarAccion"); // NOI18N
        botonAgregarAccion.setBounds(563, 210, 110, 23);
        paneComandoMascara.add(botonAgregarAccion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneComandoMascara.setBounds(0, 0, 680, 260);
        paneComandosFaciles.add(paneComandoMascara, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneComandosFaciles.setBounds(20, 30, 680, 250);
        mainPane.add(paneComandosFaciles, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(mainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 710, 290));

        botonCancelar.setText(resourceMap.getString("botonCancelar.text")); // NOI18N
        botonCancelar.setName("botonCancelar"); // NOI18N
        getContentPane().add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, -1, -1));

        botonAceptar.setText(resourceMap.getString("botonAceptar.text")); // NOI18N
        botonAceptar.setName("botonAceptar"); // NOI18N
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameComandos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAgregarAccion;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JComboBox comboAccion;
    private javax.swing.JComboBox comboCampoFinal;
    private javax.swing.JComboBox comboCampoInicial;
    private javax.swing.JComboBox comboEfecto;
    private javax.swing.JComboBox comboSeleccionFormulario;
    private javax.swing.JComboBox comboTipo;
    private javax.swing.JTextField fieldAccion;
    private javax.swing.JTextField fieldDescripcion;
    private javax.swing.JTextField fieldEfecto;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JLabel labelCampoFinal;
    private javax.swing.JLabel labelCampoInicial;
    private javax.swing.JLabel labelCondAccion;
    private javax.swing.JLabel labelCondFinal;
    private javax.swing.JLabel labelCondicionInicial;
    private javax.swing.JLabel labelCondicionInicial1;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSeleccionFormulario;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLayeredPane mainPane;
    private javax.swing.JLayeredPane paneAccionCombo;
    private javax.swing.JLayeredPane paneAccionField;
    private javax.swing.JLayeredPane paneComandoMascara;
    private javax.swing.JLayeredPane paneComandosFaciles;
    private javax.swing.JLayeredPane paneDivisionAccion;
    private javax.swing.JLayeredPane paneDivisionEfecto;
    private javax.swing.JLayeredPane paneEfectoCombo;
    private javax.swing.JLayeredPane paneEfectoField;
    // End of variables declaration//GEN-END:variables

}
