        /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frameLista.java
 *
 * Created on 17/04/2009, 08:57:58 PM luiscarlosch@gmail.com
 */
package gestiontipocampo;

import javax.swing.*;
import java.*;

/**
 *
 * @author Administrator
 */
public class frameLista extends javax.swing.JFrame {

    /** Creates new form frameLista */
    public Lista miLista;
    //   public String elementoSeleccionado;
    //  private int IDTipoCampo;
    public boolean modificando;

    public frameLista() {
        initComponents();
        SidePanel.setVisible(false);
        miLista = new Lista();
    }

    public frameLista(int IDLista) {
        initComponents();
        miLista = new Lista();
        campoEntrada.setText("");
        campoEntrada.requestFocus();
        //this.IDTipoCampo=IDLista;
        miLista.correlativo = IDLista;
        miLista.setLista();
        this.actualizarLista();

        etiquetaNombreLista.setText(miLista.getNombre());
        etiquetaDescripcionLista.setText(miLista.getDescripcion());
        nombreMiembroPorDefecto.setText(miLista.nombreMiembroPorDefecto);
    }

    public void actualizarLista() {
        if (miLista.ordenPersonalizado==true) {
            SidePanel.setVisible(true);
        } else {
            SidePanel.setVisible(false);
        }
        lista.setListData(miLista.setAndGetMiembrosVectorActualizados());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        LabelPanel = new javax.swing.JPanel();
        etiquetaNombreLista = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etiquetaDescripcionLista = new javax.swing.JLabel();
        nombreMiembroPorDefecto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButtonPanel = new javax.swing.JPanel();
        botonAgregar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonPorDefecto = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        campoEntrada = new javax.swing.JTextField();
        SidePanel = new javax.swing.JPanel();
        botonTop = new javax.swing.JButton();
        botonUp = new javax.swing.JButton();
        botonDown = new javax.swing.JButton();
        botonBottom = new javax.swing.JButton();
        panelBotonPersonalizado = new javax.swing.JPanel();
        botonPersonalizado = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Form"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        lista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "aasdfasf", "asdfasf", "asdfasdf", "asfasdfsadf", "asdfsfdsadf", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista.setName("lista"); // NOI18N
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 300, 210));

        LabelPanel.setName("LabelPanel"); // NOI18N
        LabelPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameLista.class);
        etiquetaNombreLista.setText(resourceMap.getString("etiquetaNombreLista.text")); // NOI18N
        etiquetaNombreLista.setName("etiquetaNombreLista"); // NOI18N
        LabelPanel.add(etiquetaNombreLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        LabelPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        LabelPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        etiquetaDescripcionLista.setText(resourceMap.getString("etiquetaDescripcionLista.text")); // NOI18N
        etiquetaDescripcionLista.setName("etiquetaDescripcionLista"); // NOI18N
        LabelPanel.add(etiquetaDescripcionLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        nombreMiembroPorDefecto.setText(resourceMap.getString("nombreMiembroPorDefecto.text")); // NOI18N
        nombreMiembroPorDefecto.setName("nombreMiembroPorDefecto"); // NOI18N
        LabelPanel.add(nombreMiembroPorDefecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        LabelPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        getContentPane().add(LabelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 330, 40));

        ButtonPanel.setName("ButtonPanel"); // NOI18N
        ButtonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAgregar.setText(resourceMap.getString("botonAgregar.text")); // NOI18N
        botonAgregar.setEnabled(false);
        botonAgregar.setName("botonAgregar"); // NOI18N
        botonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAgregarMouseClicked(evt);
            }
        });
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        ButtonPanel.add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));
        botonAgregar.getAccessibleContext().setAccessibleName(resourceMap.getString("jButton1.AccessibleContext.accessibleName")); // NOI18N

        botonBorrar.setText(resourceMap.getString("botonBorrar.text")); // NOI18N
        botonBorrar.setEnabled(false);
        botonBorrar.setName("botonBorrar"); // NOI18N
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });
        ButtonPanel.add(botonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        botonPorDefecto.setText(resourceMap.getString("botonPorDefecto.text")); // NOI18N
        botonPorDefecto.setEnabled(false);
        botonPorDefecto.setName("botonPorDefecto"); // NOI18N
        botonPorDefecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPorDefectoMouseClicked(evt);
            }
        });
        ButtonPanel.add(botonPorDefecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        botonSalir.setText(resourceMap.getString("botonSalir.text")); // NOI18N
        botonSalir.setName("botonSalir"); // NOI18N
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });
        ButtonPanel.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        campoEntrada.setText(resourceMap.getString("campoEntrada.text")); // NOI18N
        campoEntrada.setName("campoEntrada"); // NOI18N
        campoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEntradaActionPerformed(evt);
            }
        });
        campoEntrada.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                campoEntradaInputMethodTextChanged(evt);
            }
        });
        campoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoEntradaKeyTyped(evt);
            }
        });
        ButtonPanel.add(campoEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        getContentPane().add(ButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 320, 60));

        SidePanel.setMaximumSize(new java.awt.Dimension(43, 137));
        SidePanel.setMinimumSize(new java.awt.Dimension(43, 137));
        SidePanel.setName("SidePanel"); // NOI18N
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getActionMap(frameLista.class, this);
        botonTop.setAction(actionMap.get("botonPrimeroAccion")); // NOI18N
        botonTop.setText(resourceMap.getString("botonTop.text")); // NOI18N
        botonTop.setName("botonTop"); // NOI18N
        botonTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTopActionPerformed(evt);
            }
        });
        SidePanel.add(botonTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 30, -1));

        botonUp.setAction(actionMap.get("botonSubirAccion")); // NOI18N
        botonUp.setText(resourceMap.getString("botonUp.text")); // NOI18N
        botonUp.setName("botonUp"); // NOI18N
        SidePanel.add(botonUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        botonDown.setAction(actionMap.get("botonBajarAccion")); // NOI18N
        botonDown.setText(resourceMap.getString("botonDown.text")); // NOI18N
        botonDown.setName("botonDown"); // NOI18N
        SidePanel.add(botonDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 30, -1));

        botonBottom.setAction(actionMap.get("botonUltimoAccion")); // NOI18N
        botonBottom.setText(resourceMap.getString("botonBottom.text")); // NOI18N
        botonBottom.setName("botonBottom"); // NOI18N
        SidePanel.add(botonBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 30, -1));

        getContentPane().add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 50, 150));
        SidePanel.getAccessibleContext().setAccessibleDescription(resourceMap.getString("SidePanel.AccessibleContext.accessibleDescription")); // NOI18N

        panelBotonPersonalizado.setName("panelBotonPersonalizado"); // NOI18N
        panelBotonPersonalizado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPersonalizado.setAction(actionMap.get("botonOrdenPersonalizado")); // NOI18N
        botonPersonalizado.setName("botonPersonalizado"); // NOI18N
        panelBotonPersonalizado.add(botonPersonalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 30));

        getContentPane().add(panelBotonPersonalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 30, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMouseClicked
}//GEN-LAST:event_botonAgregarMouseClicked

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        this.dispose();
}//GEN-LAST:event_botonSalirMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        //     lista.setListData(this.miLista.getModeloVector("select valor, IDLista from MIEMBROLISTA ml, LISTA l where ml.IDLista=l.correlativo and l.correlativo=31", "valor", "IDLIsta"));
    }//GEN-LAST:event_formComponentShown

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listaValueChanged

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        JOptionPane.showMessageDialog(null, "No se puede eliminar el elemento por defecto.");
        String[] opciones = {"Si", "No"};
        int respuesta = JOptionPane.showOptionDialog(null, "¿Está seguro de que desea borrar esta entrada?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, opciones, "No");

        switch (respuesta) {
            case 0:
                //miLista.borrarMiembro(((MiDato)lista.getSelectedValue()).ID+"");
                miLista.borrarMiembro(lista.getSelectedValue());
                // this.actualizarLista();
                lista.setListData(miLista.getModeloMiembrosVector());
                setConfiguracionBase();
                break;
            case 1:
                /*No quiso borrar*/
                break;
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
        if (evt.getClickCount() == 2) {
            modificando = true;
            botonBorrar.setEnabled(false);
            botonPorDefecto.setEnabled(false);
            if (lista.getSelectedValue() != null) {
                campoEntrada.setText(lista.getSelectedValue().toString());
                botonAgregar.setEnabled(true);
                botonAgregar.setText("Modificar");
            } else {
                campoEntrada.setText("");
            }
            campoEntrada.requestFocus();
        } else {
            botonAgregar.setText("Agregar");
            modificando = false;
            botonAgregar.setEnabled(false);
            botonBorrar.setEnabled(true);
            botonPorDefecto.setEnabled(true);
            campoEntrada.setText("");
        }

        this.campoEntrada.setText(this.campoEntrada.getText().trim());

    //   System.out.print(evt.getClickCount()+".");
    }//GEN-LAST:event_listaMouseClicked

    private void botonPorDefectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPorDefectoMouseClicked
        try {
            miLista.IDMiembroPorDefecto = (((MiDato) lista.getSelectedValue()).ID) + "";
            miLista.upDateIDMiembroPorDefecto((((MiDato) lista.getSelectedValue()).ID) + "");
        } catch (java.lang.ClassCastException e) {
            try {
                miLista.IDMiembroPorDefecto = (((MiDato2) lista.getSelectedValue()).ID) + "";
                miLista.upDateIDMiembroPorDefecto((((MiDato2) lista.getSelectedValue()).ID) + "");
            } catch (java.lang.ClassCastException e2) {
            }
        }


        lista.setListData(miLista.getModeloMiembrosVector());
        miLista.setLista();
        nombreMiembroPorDefecto.setText(miLista.nombreMiembroPorDefecto);
        this.setConfiguracionBase();
    }//GEN-LAST:event_botonPorDefectoMouseClicked

    private void campoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEntradaActionPerformed
    }//GEN-LAST:event_campoEntradaActionPerformed

    private void campoEntradaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_campoEntradaInputMethodTextChanged
    }//GEN-LAST:event_campoEntradaInputMethodTextChanged

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed

        if (miLista.getMiembroListaSet().contains(new MiDato(campoEntrada.getText(), 0))) {
            
            JOptionPane.showMessageDialog(null, "Ya existe un elemento con ese nombre.");
        } else {
            if (modificando) {
                miLista.upDateValorMiembro(lista.getSelectedValue(), campoEntrada.getText());
                lista.setListData(miLista.getModeloMiembrosVector());
                this.nombreMiembroPorDefecto.setText(miLista.nombreMiembroPorDefecto);
                setConfiguracionBase();
                modificando = false;
            } else {
                miLista.agregarMiembro(campoEntrada.getText(), lista.getModel().getSize());
                //elementoSeleccionado=campoEntrada.getText();
                this.actualizarLista();
                this.setConfiguracionBase();

            }


            //  campoEntrada.requestFocus();        // TODO add your handling code here:
            botonAgregar.setText("Agregar");
        }
        campoEntrada.requestFocus();
    }//GEN-LAST:event_botonAgregarActionPerformed

    public void setConfiguracionBase() {
        campoEntrada.setText("");
        campoEntrada.requestFocus();
        botonAgregar.setEnabled(false);
        botonBorrar.setEnabled(false);
        botonPorDefecto.setEnabled(false);
    }

    private void campoEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEntradaKeyTyped
        if (!this.modificando) {
            lista.clearSelection();
        }
        botonAgregar.setEnabled(true);        // TODO add your handling code here:
        if (campoEntrada.getText().trim().isEmpty()) {
            botonAgregar.setEnabled(false);
        }
    }//GEN-LAST:event_campoEntradaKeyTyped

    private void botonTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTopActionPerformed
    }//GEN-LAST:event_botonTopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frameLista().setVisible(true);
            }
        });
    }

    private int getID(Object obj) {
        int ID = 0;
        try {
            ID = ((MiDato) obj).ID;
        } catch (java.lang.ClassCastException e) {
            try {
                ID = ((MiDato2) obj).ID;
            } catch (java.lang.ClassCastException ex) {
            }
        }
        return ID;
    }

        @org.jdesktop.application.Action
    public void botonOrdenPersonalizado() {
        if (botonPersonalizado.isSelected()) {
            miLista.setConOrdenPersonalizado(true);
        } else {
            miLista.setConOrdenPersonalizado(false);
        }
        this.actualizarLista();
    }

    @org.jdesktop.application.Action
    public void botonPrimeroAccion() {
        int posicion = lista.getSelectedIndex();
        int ID = 0;
        ListModel otraLista = lista.getModel();
        ID = getID(otraLista.getElementAt(posicion));

        for (int i = 0; i < posicion; i++) {
            try {
                int correlativo = getID(otraLista.getElementAt(i));
                miLista.setOrdenDeElemento(correlativo, i + 1);
            } catch (java.lang.ClassCastException ex) {
            }
        }
        miLista.setOrdenDeElemento(ID, 0);
        this.actualizarLista();
    }

    @org.jdesktop.application.Action
    public void botonSubirAccion() {
        int posicion = lista.getSelectedIndex();
        int ID = 0;
        ListModel otraLista = lista.getModel();
        ID = getID(otraLista.getElementAt(posicion));
        if (posicion > 0) {
            try {
                int correlativo = getID(otraLista.getElementAt(posicion - 1));
                miLista.setOrdenDeElemento(correlativo, posicion);
            } catch (java.lang.ClassCastException ex) {
            }
            miLista.setOrdenDeElemento(ID, posicion - 1);
            this.actualizarLista();
        }
    }

    @org.jdesktop.application.Action
    public void botonBajarAccion() {
        int posicion = lista.getSelectedIndex();
        int ID = 0;
        ListModel otraLista = lista.getModel();
        ID = getID(otraLista.getElementAt(posicion));
        if (posicion < otraLista.getSize() - 1) {
            try {
                int correlativo = getID(otraLista.getElementAt(posicion + 1));
                miLista.setOrdenDeElemento(correlativo, posicion);
            } catch (java.lang.ClassCastException ex) {
            }
            miLista.setOrdenDeElemento(ID, posicion + 1);
            this.actualizarLista();
        }
    }

    @org.jdesktop.application.Action
    public void botonUltimoAccion() {
        int posicion = lista.getSelectedIndex();
        int posFinal;
        int ID = 0;
        ListModel otraLista = lista.getModel();
        posFinal = otraLista.getSize() - 1;
        ID = getID(otraLista.getElementAt(posicion));

        for (int i = posFinal; i > posicion; i--) {
            try {
                int correlativo = getID(otraLista.getElementAt(i));
                miLista.setOrdenDeElemento(correlativo, i - 1);
            } catch (java.lang.ClassCastException ex) {
            }
        }
        miLista.setOrdenDeElemento(ID, posFinal);
        this.actualizarLista();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel LabelPanel;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBottom;
    private javax.swing.JButton botonDown;
    private javax.swing.JToggleButton botonPersonalizado;
    private javax.swing.JButton botonPorDefecto;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonTop;
    private javax.swing.JButton botonUp;
    private javax.swing.JTextField campoEntrada;
    private javax.swing.JLabel etiquetaDescripcionLista;
    private javax.swing.JLabel etiquetaNombreLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lista;
    private javax.swing.JLabel nombreMiembroPorDefecto;
    private javax.swing.JPanel panelBotonPersonalizado;
    // End of variables declaration//GEN-END:variables
}
