/*
 * frameFormulario.java
 *
 * Created on 30-abr-2009, 18:16:02
 */

package gestiontipocampo;

import java.sql.*;
import javax.swing.tree.*;
import javax.swing.JTree;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import javax.swing.*;
import javax.swing.JColorChooser;
import java.awt.Color;

/**
 *
 * @author Alberto
 */
public class frameFormulario extends javax.swing.JFrame {

    /** Creates new form frameFormulario */
    public frameFormulario( ) {

        String nombre = JOptionPane.showInputDialog(this, "Favor ingresar el nombre del formulario a crear", "", JOptionPane.QUESTION_MESSAGE);
        String descripcion = JOptionPane.showInputDialog(this, "Favor ingresar la descripcion del formulario a crear", "", JOptionPane.QUESTION_MESSAGE);

        miFormulario = new Formulario( nombre, descripcion );
        initComponents();

        //Inicializa los recolectores de eventos del mouse
        listener = new DragMouseAdapter();
        motionListener= new DragMouseAdapter();

        //Inicializa el arbol para obtener nodo seleccionado
        arbolPrincipal.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        llenarTreeView();
        ocultarPanes();
    }

    /** Creates new form frameFormulario */
    public frameFormulario( TreeModel arbolHeredado) {

        String nombre = JOptionPane.showInputDialog(this, "Favor ingresar el nombre del formulario a crear", "", JOptionPane.QUESTION_MESSAGE);
        String descripcion = JOptionPane.showInputDialog(this, "Favor ingresar la descripcion del formulario a crear", "", JOptionPane.QUESTION_MESSAGE);

        miFormulario = new Formulario( nombre, descripcion );
        initComponents();

        //Inicializa los recolectores de eventos del mouse
        listener = new DragMouseAdapter();
        motionListener= new DragMouseAdapter();

        //Inicializa el arbol para obtener nodo seleccionado
        arbolPrincipal.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);

        arbolPrincipal.setModel(arbolHeredado);
        ocultarPanes();

        jButton1.addMouseListener(listener);
        jCheckBox1.addMouseListener(listener);
        jTextField1.addMouseListener(listener);

        jButton1.addMouseMotionListener(motionListener);
        jCheckBox1.addMouseMotionListener(motionListener);
        jTextField1.addMouseMotionListener(motionListener);
    }

    private class DragMouseAdapter extends MouseAdapter {
        @Override
        public void mousePressed(MouseEvent e){
            System.out.println("Se dio click al mouse");
            JComponent c = (JComponent)e.getSource();          
            //  mostrarDatosComponente( c.getName()); //tuve q comentarlo xq se jodia el mover los iconos
            //Aqui hay q mostrar los valores del componente...
        }

        @Override
        public void mouseDragged(MouseEvent e) {
            JComponent c = (JComponent)e.getSource();
            maxX = frameVistaPrevia.getWidth();
            maxY = frameVistaPrevia.getHeight();
            float tx = e.getX();
            if(tx < 0) { tx = 0; }
            if(tx > maxX - c.getWidth()) { tx = maxX-c.getWidth(); }

            float ty = e.getY();
            if(ty < 0) { ty = 0; }
            if(ty > maxY-c.getHeight()) { ty = maxY-c.getHeight(); }
            c.setBounds((int)tx, (int)ty, c.getWidth(), c.getHeight() );
        }

        @Override
        public void mouseReleased(MouseEvent e){
            System.out.println("Se solto el mouse");
            JComponent c = (JComponent)e.getSource();
            //Aqui hay q guardar los nuevos valores a la BD...
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        arbolPrincipal = new javax.swing.JTree();
        paneDatos = new javax.swing.JLayeredPane();
        panePrincipal = new javax.swing.JLayeredPane();
        botonAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        valorNombreGeneral = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        valorNota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboTipos = new javax.swing.JComboBox();
        paneBinario = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        valorNombreBinario1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        valorOpcionBinaria1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        valorNombreBinario2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        valorOpcionBinaria2 = new javax.swing.JTextField();
        radioOpcionBinaria1 = new javax.swing.JRadioButton();
        radioOpcionBinaria2 = new javax.swing.JRadioButton();
        paneNumero = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        valorNumDecimales = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        valorNumeroMascara = new javax.swing.JTextField();
        valorValorDefectoNumero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        paneIncremental = new javax.swing.JLayeredPane();
        jLabel17 = new javax.swing.JLabel();
        valorValorInicial = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        valorIncremento = new javax.swing.JTextField();
        paneFechaHora = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        valorPreaviso = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        valorFechaDefecto = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        radioFechaHoraSi = new javax.swing.JRadioButton();
        radioFechaHoraNo = new javax.swing.JRadioButton();
        comboFormatoFecha = new javax.swing.JComboBox();
        paneJerarquia = new javax.swing.JLayeredPane();
        labelCategorias = new javax.swing.JLabel();
        comboCategorias = new javax.swing.JComboBox();
        radioNivelesSi = new javax.swing.JRadioButton();
        radioNivelesNo = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        radioCategoriasSi = new javax.swing.JRadioButton();
        radioCategoriasNo = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        radioNomUnicoSi = new javax.swing.JRadioButton();
        radioNomUnicoNo = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        comboNiveles = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        valorNumNiveles = new javax.swing.JTextField();
        valorNumTerminos = new javax.swing.JTextField();
        paneTexto = new javax.swing.JLayeredPane();
        jLabel16 = new javax.swing.JLabel();
        valorTextoLargo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        valorTextoDefecto = new javax.swing.JTextField();
        paneLista = new javax.swing.JLayeredPane();
        valorPorDefectoLista = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        paneFormulario = new javax.swing.JLayeredPane();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        comboTipoLetra = new javax.swing.JComboBox();
        colorDato = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        tamanoLetra = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        valorDato = new javax.swing.JTextField();
        valEjeY = new javax.swing.JTextField();
        valEjeX = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        bottonColor = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        frameVistaPrevia = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Tipos Campo");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Número");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Binario");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("FechaHora");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Texto");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Incremental");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Jerarquía");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Lista");
        treeNode1.add(treeNode2);
        arbolPrincipal.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbolPrincipal.setName("arbolPrincipal"); // NOI18N
        arbolPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolPrincipalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(arbolPrincipal);

        paneDatos.setName("paneDatos"); // NOI18N

        panePrincipal.setAutoscrolls(true);
        panePrincipal.setName("panePrincipal"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gestiontipocampo.GestionTipoCampoApp.class).getContext().getResourceMap(frameFormulario.class);
        botonAgregar.setText(resourceMap.getString("botonAgregar.text")); // NOI18N
        botonAgregar.setName("botonAgregar"); // NOI18N
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        botonAgregar.setBounds(290, 340, 80, 23);
        panePrincipal.add(botonAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setBounds(20, 70, 41, 14);
        panePrincipal.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorNombreGeneral.setEditable(false);
        valorNombreGeneral.setName("valorNombreGeneral"); // NOI18N
        valorNombreGeneral.setBounds(20, 90, 120, 20);
        panePrincipal.add(valorNombreGeneral, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setBounds(200, 70, 58, 14);
        panePrincipal.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorNota.setEditable(false);
        valorNota.setName("valorNota"); // NOI18N
        valorNota.setBounds(200, 90, 120, 20);
        panePrincipal.add(valorNota, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setBounds(20, 20, 73, 14);
        panePrincipal.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comboTipos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Número", "Binario", "FechaHora", "Texto", "Incremental", "Jerarquia", "Lista" }));
        comboTipos.setEnabled(false);
        comboTipos.setFocusable(false);
        comboTipos.setName("comboTipos"); // NOI18N
        comboTipos.setBounds(20, 40, 120, 20);
        panePrincipal.add(comboTipos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneBinario.setName("paneBinario"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setBounds(10, 10, 100, 20);
        paneBinario.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorNombreBinario1.setEditable(false);
        valorNombreBinario1.setName("valorNombreBinario1"); // NOI18N
        valorNombreBinario1.setBounds(10, 30, 120, 20);
        paneBinario.add(valorNombreBinario1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setBounds(200, 10, 100, 20);
        paneBinario.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorOpcionBinaria1.setEditable(false);
        valorOpcionBinaria1.setName("valorOpcionBinaria1"); // NOI18N
        valorOpcionBinaria1.setBounds(200, 30, 120, 20);
        paneBinario.add(valorOpcionBinaria1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        jLabel9.setBounds(10, 120, 100, 20);
        paneBinario.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setBounds(10, 60, 120, 20);
        paneBinario.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorNombreBinario2.setEditable(false);
        valorNombreBinario2.setName("valorNombreBinario2"); // NOI18N
        valorNombreBinario2.setBounds(10, 80, 120, 20);
        paneBinario.add(valorNombreBinario2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        jLabel11.setBounds(200, 60, 100, 20);
        paneBinario.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorOpcionBinaria2.setEditable(false);
        valorOpcionBinaria2.setName("valorOpcionBinaria2"); // NOI18N
        valorOpcionBinaria2.setBounds(200, 80, 120, 20);
        paneBinario.add(valorOpcionBinaria2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radioOpcionBinaria1.setSelected(true);
        radioOpcionBinaria1.setText(resourceMap.getString("radioOpcionBinaria1.text")); // NOI18N
        radioOpcionBinaria1.setEnabled(false);
        radioOpcionBinaria1.setFocusable(false);
        radioOpcionBinaria1.setName("radioOpcionBinaria1"); // NOI18N
        radioOpcionBinaria1.setBounds(10, 140, 100, 20);
        paneBinario.add(radioOpcionBinaria1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radioOpcionBinaria2.setText(resourceMap.getString("radioOpcionBinaria2.text")); // NOI18N
        radioOpcionBinaria2.setEnabled(false);
        radioOpcionBinaria2.setFocusable(false);
        radioOpcionBinaria2.setName("radioOpcionBinaria2"); // NOI18N
        radioOpcionBinaria2.setBounds(10, 170, 100, 20);
        paneBinario.add(radioOpcionBinaria2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneBinario.setBounds(20, 110, 390, 210);
        panePrincipal.add(paneBinario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneNumero.setName("paneNumero"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setBounds(10, 10, 110, 14);
        paneNumero.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorNumDecimales.setEditable(false);
        valorNumDecimales.setName("valorNumDecimales"); // NOI18N
        valorNumDecimales.setBounds(10, 30, 120, 20);
        paneNumero.add(valorNumDecimales, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jLabel5.setBounds(200, 10, 50, 14);
        paneNumero.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorNumeroMascara.setEditable(false);
        valorNumeroMascara.setName("valorNumeroMascara"); // NOI18N
        valorNumeroMascara.setBounds(200, 30, 120, 20);
        paneNumero.add(valorNumeroMascara, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorValorDefectoNumero.setEditable(false);
        valorValorDefectoNumero.setText(resourceMap.getString("valorValorDefectoNumero.text")); // NOI18N
        valorValorDefectoNumero.setName("valorValorDefectoNumero"); // NOI18N
        valorValorDefectoNumero.setBounds(10, 80, 120, 20);
        paneNumero.add(valorValorDefectoNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        jLabel12.setBounds(10, 60, 90, 14);
        paneNumero.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneNumero.setBounds(20, 110, 410, 200);
        panePrincipal.add(paneNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneIncremental.setName("paneIncremental"); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N
        jLabel17.setBounds(20, 10, 100, 20);
        paneIncremental.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorValorInicial.setEditable(false);
        valorValorInicial.setName("valorValorInicial"); // NOI18N
        valorValorInicial.setBounds(20, 30, 120, 20);
        paneIncremental.add(valorValorInicial, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N
        jLabel19.setBounds(210, 10, 100, 20);
        paneIncremental.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorIncremento.setEditable(false);
        valorIncremento.setName("valorIncremento"); // NOI18N
        valorIncremento.setBounds(210, 30, 120, 20);
        paneIncremental.add(valorIncremento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneIncremental.setBounds(10, 110, 440, 190);
        panePrincipal.add(paneIncremental, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneFechaHora.setName("paneFechaHora"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setBounds(10, 20, 100, 10);
        paneFechaHora.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorPreaviso.setEditable(false);
        valorPreaviso.setName("valorPreaviso"); // NOI18N
        valorPreaviso.setBounds(200, 90, 120, -1);
        paneFechaHora.add(valorPreaviso, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        jLabel13.setBounds(200, 20, 100, -1);
        paneFechaHora.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorFechaDefecto.setEditable(false);
        valorFechaDefecto.setText(resourceMap.getString("valorFechaDefecto.text")); // NOI18N
        valorFechaDefecto.setName("valorFechaDefecto"); // NOI18N
        valorFechaDefecto.setBounds(200, 40, 120, -1);
        paneFechaHora.add(valorFechaDefecto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        jLabel14.setBounds(200, 70, 100, -1);
        paneFechaHora.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N
        jLabel15.setBounds(10, 70, 100, -1);
        paneFechaHora.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radioFechaHoraSi.setSelected(true);
        radioFechaHoraSi.setText(resourceMap.getString("radioFechaHoraSi.text")); // NOI18N
        radioFechaHoraSi.setEnabled(false);
        radioFechaHoraSi.setFocusable(false);
        radioFechaHoraSi.setName("radioFechaHoraSi"); // NOI18N
        radioFechaHoraSi.setBounds(10, 90, -1, -1);
        paneFechaHora.add(radioFechaHoraSi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radioFechaHoraNo.setText(resourceMap.getString("radioFechaHoraNo.text")); // NOI18N
        radioFechaHoraNo.setEnabled(false);
        radioFechaHoraNo.setFocusable(false);
        radioFechaHoraNo.setName("radioFechaHoraNo"); // NOI18N
        radioFechaHoraNo.setBounds(10, 110, -1, 20);
        paneFechaHora.add(radioFechaHoraNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comboFormatoFecha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dd/mm/aaaa", "mm/dd/aaaa", "aaaa/dd/mm", "aaaa/mm/dd" }));
        comboFormatoFecha.setEnabled(false);
        comboFormatoFecha.setFocusable(false);
        comboFormatoFecha.setName("comboFormatoFecha"); // NOI18N
        comboFormatoFecha.setBounds(10, 40, 90, -1);
        paneFechaHora.add(comboFormatoFecha, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneFechaHora.setBounds(20, 100, 340, 220);
        panePrincipal.add(paneFechaHora, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneJerarquia.setName("paneJerarquia"); // NOI18N
        paneJerarquia.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                paneJerarquiaComponentShown(evt);
            }
        });

        labelCategorias.setText(resourceMap.getString("labelCategorias.text")); // NOI18N
        labelCategorias.setName("labelCategorias"); // NOI18N
        labelCategorias.setBounds(200, 70, 60, 14);
        paneJerarquia.add(labelCategorias, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comboCategorias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1- Categoria 1", "2- Categoria 2", "3- Categoría 3", "4- Categoría 4" }));
        comboCategorias.setEnabled(false);
        comboCategorias.setName("comboCategorias"); // NOI18N
        comboCategorias.setBounds(200, 90, 130, 20);
        paneJerarquia.add(comboCategorias, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radioNivelesSi.setText(resourceMap.getString("radioNivelesSi.text")); // NOI18N
        radioNivelesSi.setEnabled(false);
        radioNivelesSi.setName("radioNivelesSi"); // NOI18N
        radioNivelesSi.setBounds(20, 40, 33, 23);
        paneJerarquia.add(radioNivelesSi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radioNivelesNo.setText(resourceMap.getString("radioNivelesNo.text")); // NOI18N
        radioNivelesNo.setEnabled(false);
        radioNivelesNo.setName("radioNivelesNo"); // NOI18N
        radioNivelesNo.setBounds(60, 40, 50, 23);
        paneJerarquia.add(radioNivelesNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N
        jLabel21.setBounds(20, 20, 130, 14);
        paneJerarquia.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radioCategoriasSi.setText(resourceMap.getString("radioCategoriasSi.text")); // NOI18N
        radioCategoriasSi.setEnabled(false);
        radioCategoriasSi.setName("radioCategoriasSi"); // NOI18N
        radioCategoriasSi.setBounds(20, 90, 33, 23);
        paneJerarquia.add(radioCategoriasSi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radioCategoriasNo.setText(resourceMap.getString("radioCategoriasNo.text")); // NOI18N
        radioCategoriasNo.setEnabled(false);
        radioCategoriasNo.setName("radioCategoriasNo"); // NOI18N
        radioCategoriasNo.setBounds(60, 90, 50, 23);
        paneJerarquia.add(radioCategoriasNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N
        jLabel22.setBounds(20, 70, 80, 14);
        paneJerarquia.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radioNomUnicoSi.setText(resourceMap.getString("radioNomUnicoSi.text")); // NOI18N
        radioNomUnicoSi.setEnabled(false);
        radioNomUnicoSi.setName("radioNomUnicoSi"); // NOI18N
        radioNomUnicoSi.setBounds(20, 140, 33, 23);
        paneJerarquia.add(radioNomUnicoSi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radioNomUnicoNo.setText(resourceMap.getString("radioNomUnicoNo.text")); // NOI18N
        radioNomUnicoNo.setEnabled(false);
        radioNomUnicoNo.setName("radioNomUnicoNo"); // NOI18N
        radioNomUnicoNo.setBounds(60, 140, 50, 23);
        paneJerarquia.add(radioNomUnicoNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N
        jLabel23.setBounds(20, 120, 70, 14);
        paneJerarquia.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N
        jLabel20.setBounds(200, 20, 34, 14);
        paneJerarquia.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comboNiveles.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1- Categoria 1", "2- Categoria 2", "3- Categoría 3", "4- Categoría 4" }));
        comboNiveles.setEnabled(false);
        comboNiveles.setName("comboNiveles"); // NOI18N
        comboNiveles.setBounds(200, 40, 130, 20);
        paneJerarquia.add(comboNiveles, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N
        jLabel24.setBounds(200, 170, 110, 14);
        paneJerarquia.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N
        jLabel25.setBounds(20, 170, 110, 14);
        paneJerarquia.add(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorNumNiveles.setEnabled(false);
        valorNumNiveles.setName("valorNumNiveles"); // NOI18N
        valorNumNiveles.setBounds(200, 190, 70, 20);
        paneJerarquia.add(valorNumNiveles, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorNumTerminos.setEnabled(false);
        valorNumTerminos.setName("valorNumTerminos"); // NOI18N
        valorNumTerminos.setBounds(20, 190, 70, 20);
        paneJerarquia.add(valorNumTerminos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneJerarquia.setBounds(20, 110, 390, 250);
        panePrincipal.add(paneJerarquia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneTexto.setName("paneTexto"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N
        jLabel16.setBounds(10, 10, 100, 20);
        paneTexto.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorTextoLargo.setEditable(false);
        valorTextoLargo.setName("valorTextoLargo"); // NOI18N
        valorTextoLargo.setBounds(10, 30, 120, 20);
        paneTexto.add(valorTextoLargo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N
        jLabel18.setBounds(190, 10, 100, 20);
        paneTexto.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorTextoDefecto.setEditable(false);
        valorTextoDefecto.setName("valorTextoDefecto"); // NOI18N
        valorTextoDefecto.setBounds(190, 30, 120, 20);
        paneTexto.add(valorTextoDefecto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneTexto.setBounds(10, 110, 360, 220);
        panePrincipal.add(paneTexto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneLista.setName("paneLista"); // NOI18N

        valorPorDefectoLista.setEditable(false);
        valorPorDefectoLista.setName("valorPorDefectoLista"); // NOI18N
        valorPorDefectoLista.setBounds(20, 40, 110, -1);
        paneLista.add(valorPorDefectoLista, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N
        jLabel26.setBounds(20, 20, 90, -1);
        paneLista.add(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneLista.setBounds(0, 120, 400, 160);
        panePrincipal.add(paneLista, javax.swing.JLayeredPane.DEFAULT_LAYER);

        panePrincipal.setBounds(10, 20, 420, 400);
        paneDatos.add(panePrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneFormulario.setName("paneFormulario"); // NOI18N

        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N
        jLabel27.setBounds(150, 80, 80, 14);
        paneFormulario.add(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel28.setText(resourceMap.getString("jLabel28.text")); // NOI18N
        jLabel28.setName("jLabel28"); // NOI18N
        jLabel28.setBounds(20, 30, 60, 14);
        paneFormulario.add(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comboTipoLetra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arial", "Times New Roman", "????????" }));
        comboTipoLetra.setName("comboTipoLetra"); // NOI18N
        comboTipoLetra.setBounds(20, 100, 80, 20);
        paneFormulario.add(comboTipoLetra, javax.swing.JLayeredPane.DEFAULT_LAYER);

        colorDato.setEditable(false);
        colorDato.setText(resourceMap.getString("colorDato.text")); // NOI18N
        colorDato.setName("colorDato"); // NOI18N
        colorDato.setBounds(150, 50, 60, 20);
        paneFormulario.add(colorDato, javax.swing.JLayeredPane.DEFAULT_LAYER);

        botonGuardar.setText(resourceMap.getString("botonGuardar.text")); // NOI18N
        botonGuardar.setName("botonGuardar"); // NOI18N
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        botonGuardar.setBounds(30, 180, 71, 23);
        paneFormulario.add(botonGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tamanoLetra.setText(resourceMap.getString("tamanoLetra.text")); // NOI18N
        tamanoLetra.setName("tamanoLetra"); // NOI18N
        tamanoLetra.setBounds(150, 100, 80, 20);
        paneFormulario.add(tamanoLetra, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel29.setText(resourceMap.getString("jLabel29.text")); // NOI18N
        jLabel29.setName("jLabel29"); // NOI18N
        jLabel29.setBounds(20, 80, 60, 14);
        paneFormulario.add(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel30.setText(resourceMap.getString("jLabel30.text")); // NOI18N
        jLabel30.setName("jLabel30"); // NOI18N
        jLabel30.setBounds(270, 80, 60, 14);
        paneFormulario.add(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valorDato.setName("valorDato"); // NOI18N
        valorDato.setBounds(20, 50, 80, 20);
        paneFormulario.add(valorDato, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valEjeY.setText(resourceMap.getString("valEjeY.text")); // NOI18N
        valEjeY.setName("valEjeY"); // NOI18N
        valEjeY.setBounds(270, 100, 50, 20);
        paneFormulario.add(valEjeY, javax.swing.JLayeredPane.DEFAULT_LAYER);

        valEjeX.setText(resourceMap.getString("valEjeX.text")); // NOI18N
        valEjeX.setName("valEjeX"); // NOI18N
        valEjeX.setBounds(270, 50, 50, 20);
        paneFormulario.add(valEjeX, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel31.setText(resourceMap.getString("jLabel31.text")); // NOI18N
        jLabel31.setName("jLabel31"); // NOI18N
        jLabel31.setBounds(150, 30, 60, 14);
        paneFormulario.add(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel32.setText(resourceMap.getString("jLabel32.text")); // NOI18N
        jLabel32.setName("jLabel32"); // NOI18N
        jLabel32.setBounds(270, 30, 60, 14);
        paneFormulario.add(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bottonColor.setText(resourceMap.getString("bottonColor.text")); // NOI18N
        bottonColor.setName("bottonColor"); // NOI18N
        bottonColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonColorActionPerformed(evt);
            }
        });
        bottonColor.setBounds(210, 50, 30, 23);
        paneFormulario.add(bottonColor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paneFormulario.setBounds(10, 110, 390, 250);
        paneDatos.add(paneFormulario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        botonActualizar.setText(resourceMap.getString("botonActualizar.text")); // NOI18N
        botonActualizar.setName("botonActualizar"); // NOI18N

        frameVistaPrevia.setIconifiable(true);
        frameVistaPrevia.setName("frameVistaPrevia"); // NOI18N
        frameVistaPrevia.setVisible(true);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N

        jCheckBox1.setText(resourceMap.getString("jCheckBox1.text")); // NOI18N
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        javax.swing.GroupLayout frameVistaPreviaLayout = new javax.swing.GroupLayout(frameVistaPrevia.getContentPane());
        frameVistaPrevia.getContentPane().setLayout(frameVistaPreviaLayout);
        frameVistaPreviaLayout.setHorizontalGroup(
            frameVistaPreviaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameVistaPreviaLayout.createSequentialGroup()
                .addGroup(frameVistaPreviaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameVistaPreviaLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton1))
                    .addGroup(frameVistaPreviaLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameVistaPreviaLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jCheckBox1)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        frameVistaPreviaLayout.setVerticalGroup(
            frameVistaPreviaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameVistaPreviaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addGap(54, 54, 54)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jCheckBox1)
                .addContainerGap(360, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(botonActualizar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paneDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(frameVistaPrevia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(1035, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonActualizar))
                    .addComponent(frameVistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paneJerarquiaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_paneJerarquiaComponentShown
        Modelo  miModelo = new Modelo();
        comboCategorias.setModel(new javax.swing.DefaultComboBoxModel(miModelo.getModeloDeCombo("select nombre, ID from TIPOCATEGORIA;")));
}//GEN-LAST:event_paneJerarquiaComponentShown

    private void arbolPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolPrincipalMouseClicked
        //actualizarPath();
        abrirNodoHoja();
}//GEN-LAST:event_arbolPrincipalMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        //Se agrega el valor al formulario
        //FALTA!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        String nombre = valorNombreGeneral.getText();
        
        //En este switch se debe crear una instancia del nuevo tipo campo a agregar al formulario
        switch(comboTipos.getSelectedIndex()){
            case 0:
                //Numero
                agregarTipoNumero(nombre);
                break;
            case 1:
                //Binario
                break;
            case 2:
                //FechaHora
                break;
            case 3:
                //Texto
                break;
            case 4:
                //Incremental
                break;
            case 5:
                //Jerarquia
                break;
            case 6:
                //Lista
                break;
            default:
                break;

        }
        //Se abre el pane de formulario
        ocultarPanes();
        paneFormulario.setVisible(true);
        valorDato.setText(nombre);
}//GEN-LAST:event_botonAgregarActionPerformed

    /**
     * Agrega al formulario un campo nuevo tipo numero
     * @param nombre
     */
    private void agregarTipoNumero(String nombre){
        //Agrega todos los otros datos por defecto
        miFormulario.agregarMiembro(nombre, 1, 1, "Arial", Color.BLACK.getRGB(), 12, Integer.parseInt(getIDTipoCampo(nombre)));

        //Esto es temporal!! se debe crear un objeto de numero...
        JTextField jtf = new JTextField(10);
        jtf.setName(nombre);
        jtf.addMouseListener(listener);
        jtf.addMouseMotionListener(motionListener);
        frameVistaPrevia.add( jtf );
        frameVistaPrevia.repaint();
    }

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        //Se tienen que guardar los datos en la tabla MIEMBROFORMULARIO
        miFormulario.upDateValoresMiembro(IDEnUso, valorDato.getText(), Integer.parseInt(valEjeX.getText()), Integer.parseInt(valEjeY.getText()), comboTipoLetra.getSelectedItem().toString() , colorDato.getForeground().getRGB() , Integer.parseInt(tamanoLetra.getText()) );
        //desp de guardar se ocultan los panes
        ocultarPanes();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void bottonColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonColorActionPerformed
        Color color = Color.BLACK;
        color = JColorChooser.showDialog( bottonColor , "Seleccione un color", color );
        // establecer color predeterminado, si no se devuelve un color
        if ( color == null )
            color = Color.BLACK;        
        // cambiar color de la letra del campo de texto
        colorDato.setForeground( color );
    }//GEN-LAST:event_bottonColorActionPerformed

    /**
     * Muestra los datos del componente, valor, tipoLetra, tamaño, etc...
     * @param nombre
     */
    public void mostrarDatosComponente( String nombre){
        ocultarPanes();
        paneFormulario.setVisible(true);

        //se llenan los datos
        valorDato.setText(nombre);
    }

    /**
     * Llena el tree view
     */
    public void llenarTreeView(){
        //Llena los valores del Tree View
        String [] tiposCampo = {"Numero", "Binario", "FechaHora", "Texto", "Incremental", "Jerarquia", "Lista"};
        String valores;
        String [] valTrim;
        DefaultMutableTreeNode nodoTipoCampo;
        DefaultMutableTreeNode nodoTemp;
        DefaultMutableTreeNode raizArbol = new DefaultMutableTreeNode("Gift");

        for(int k = 0; k < tiposCampo.length; k++){
            nodoTipoCampo = new DefaultMutableTreeNode(tiposCampo[k]);
            //Se llenan los datos con los valores que contenga la base de datos con el tipo campo:
            valores = buscarNombreEnBD(k+1);
           // System.out.println("valores: " + valores);
            valTrim = valores.split("\n");
            for(int i= 0; i < valTrim.length; ++i){
                nodoTemp = new DefaultMutableTreeNode(valTrim[i]);
                nodoTipoCampo.add(nodoTemp); //agrega el nodo
            }
            raizArbol.add(nodoTipoCampo);
        }
        JTree arbolnuevo = new JTree(raizArbol);
        arbolPrincipal.setModel(arbolnuevo.getModel());
    }

     /**
     * Encargado de buscar el valor del nombre en la base de datos
     * @param num: Indica el tipo de campo que va a buscar
     */
    public String buscarNombreEnBD(int num){
        ControladorBD buscador = new ControladorBD();
        String valores = "";
        try {
            ResultSet resultado = buscador.getResultSet("select * from TIPOCAMPO where tipo = '" + num + "';");
            if(resultado != null)
                while (resultado.next()) {
                    valores += resultado.getObject(2).toString()+"\n";
                }
        } catch (SQLException e) {
            System.out.println("*SQL Exception: *" + e.toString());
        }
        return valores;
    }

    /**
     * Muestra los panes necesarios segun lo que se vaya a mostrar
     */
    public void abrirNodoHoja(){

        DefaultMutableTreeNode node = (DefaultMutableTreeNode)arbolPrincipal.getLastSelectedPathComponent();
        if (node != null){
            String nombre = node.toString();
            String papa = node.getParent()!=null?node.getParent().toString():"";
            ocultarPanes();
            paneDatos.setVisible(true);
            panePrincipal.setVisible(true);
            if( papa.equals("Numero")  ){
                paneNumero.setVisible(true);
                llenarDatosReadOnly(nombre, 1);
            }
            else{
                if( papa.equals("Binario")  ){
                    paneBinario.setVisible(true);
                    llenarDatosReadOnly(nombre, 2);
                }
                else{
                    if( papa.equals("FechaHora")  ){
                        paneFechaHora.setVisible(true);
                        llenarDatosReadOnly(nombre, 3);
                    }
                    else{
                        if( papa.equals("Texto")  ){
                            paneTexto.setVisible(true);
                            llenarDatosReadOnly(nombre, 4);
                        }
                        else{
                            if( papa.equals("Incremental")  ){
                                paneIncremental.setVisible(true);
                                llenarDatosReadOnly(nombre, 5);
                            }
                            else{
                                if( papa.equals("Jerarquia")  ){
                                    paneJerarquia.setVisible(true);
                                    llenarDatosReadOnly(nombre, 6);
                                }
                                else{
                                    if( papa.equals("Lista") ){
                                        paneLista.setVisible(true);
                                        llenarDatosReadOnly(nombre, 7);
                                    }
                                    else{
                                        paneDatos.setVisible(false);
                                        //JOptionPane.showMessageDialog(null, "¡Favor seleccionar un dato hoja!", "", JOptionPane.ERROR_MESSAGE);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * Oculta todos los panes
     */
    public void ocultarPanes(){       
        panePrincipal.setVisible(false);
        paneBinario.setVisible(false);
        paneFechaHora.setVisible(false);
        paneTexto.setVisible(false);
        paneIncremental.setVisible(false);
        paneNumero.setVisible(false);
        paneJerarquia.setVisible(false);
        paneLista.setVisible(false);
        paneFormulario.setVisible(false);        
    }

    /**
     * Llena los datos en read-only
     * @param nombre
     * @param tipo
     */
    public void llenarDatosReadOnly(String nombre, int tipo){
        //Trae todos los valores de la tabla TIPOCAMPO
        String valoresGlobales = buscarDatosEnBD(nombre);
        String [] valoresSeparados = valoresGlobales.split(";");
        String valoresEspecificos = buscarPorTipoEnBD(Integer.parseInt(valoresSeparados[0]), tipo);
        String [] valoresEspSep = valoresEspecificos.split(";");
        comboTipos.setSelectedIndex(tipo);
        valorNombreGeneral.setText(valoresSeparados[1]);
        valorNota.setText(valoresSeparados[2]);
        switch(tipo){
            //numero
            case(1):
                valorNumDecimales.setText(valoresEspSep[1]);
                valorNumeroMascara.setText(valoresEspSep[2]);
                valorValorDefectoNumero.setText(valoresEspSep[3]);
                break;
            //binario
            case(2):
                valorNombreBinario1.setText(valoresEspSep[1]);
                valorOpcionBinaria1.setText(valoresEspSep[2]);
                valorNombreBinario2.setText(valoresEspSep[3]);
                valorOpcionBinaria2.setText(valoresEspSep[4]);
                if(valoresEspSep[5].equals("true")){
                    radioOpcionBinaria1.setSelected(true);
                    radioOpcionBinaria2.setSelected(false);
                }else{
                    radioOpcionBinaria1.setSelected(false);
                    radioOpcionBinaria2.setSelected(true);
                }
                break;
            //FechaHora
            case(3):
                //comboFormatoFecha.setSelectedItem(valoresEspSep[1]);
                valorFechaDefecto.setText(valoresEspSep[2]);
                if( valoresEspSep[3].equals("true") ){
                    radioFechaHoraSi.setSelected(true);
                    radioFechaHoraNo.setSelected(false);
                }else{
                    radioFechaHoraSi.setSelected(false);
                    radioFechaHoraNo.setSelected(true);
                }
                valorPreaviso.setText(valoresEspSep[4]);
                break;
            //Texto
            case(4):
                valorTextoDefecto.setText(valoresEspSep[1]);
                valorTextoLargo.setText(valoresEspSep[2]);
                break;
            //Incremental
            case(5):
                valorValorInicial.setText(valoresEspSep[1]);
                valorIncremento.setText(valoresEspSep[2]);
                break;
            //Jerarquia
            case(6):
                if(valoresEspSep[3].equalsIgnoreCase("true")){
                    this.radioNomUnicoSi.setSelected(false);
                    this.radioNomUnicoNo.setSelected(true);
                }else{
                    this.radioNomUnicoSi.setSelected(true);
                    this.radioNomUnicoNo.setSelected(false);
                }
                this.valorNumTerminos.setText(valoresEspSep[4]);
                this.valorNumNiveles.setText(valoresEspSep[5]);
                if(valoresEspSep[8].equalsIgnoreCase("true")){
                    this.radioCategoriasSi.setSelected(true);
                    this.radioCategoriasNo.setSelected(false);
                }else{
                    this.radioCategoriasSi.setSelected(false);
                    this.radioCategoriasNo.setSelected(true);
                }
                if(valoresEspSep[9].equalsIgnoreCase("true")){
                    this.radioNivelesSi.setSelected(true);
                    this.radioNivelesNo.setSelected(false);
                }else{
                    this.radioNivelesSi.setSelected(false);
                    this.radioNivelesNo.setSelected(true);
                }
                //this.comboCategorias.setSelectedIndex(Integer.parseInt(valoresEspSep[10]));
                break;
            //Lista
            case(7):
                valoresEspSep[1] = buscarMiembroLista( Integer.parseInt(valoresEspSep[1]));
                this.valorPorDefectoLista.setText(valoresEspSep[1].trim());
                break;

            default:
                break;
        }
    }

    /**
     * Encargado de buscar los valores TIPOCAMPO segun el nombre en la base de datos
     * @param nombre: Indica el nombre del tipo de campo que va a buscar
     */
    public String buscarDatosEnBD(String nombre){
        ControladorBD buscador = new ControladorBD();
        String valores = "";
        try {
            ResultSet resultado = buscador.getResultSet("select * from TIPOCAMPO where nombre = '" + nombre + "';");
            if(resultado.next()){
                valores += resultado.getObject(1).toString() + ";";
                valores += resultado.getObject(2).toString() + ";";
                valores += resultado.getObject(3).toString() + ";";
                valores += resultado.getObject(4).toString() + ";";
                valores += resultado.getObject(5).toString() + ";";
            }
        } catch (SQLException e) {
            System.out.println("*SQL Exception: *" + e.toString());
        }
        return valores;
    }

    /**
     * Encargado de buscar los valores TIPOCAMPO segun el nombre en la base de datos
     * @param nombre: Indica el nombre del tipo de campo que va a buscar
     */
    public String getIDTipoCampo(String nombre){
        ControladorBD buscador = new ControladorBD();
        String valores = "";
        try {
            ResultSet resultado = buscador.getResultSet("select correlativo from TIPOCAMPO where nombre = '" + nombre + "';");
            if(resultado.next()){
                valores += resultado.getObject("correlativo").toString();
            }
        } catch (SQLException e) {
            System.out.println("*SQL Exception: *" + e.toString());
        }
        return valores;
    }

    /**
     * Encargado de buscar el valor del nombre en la base de datos
     * @param ID: Indica el ID del campo que va a buscar
     * @param tipo: Indica el tipo de campo que va a buscar
     */
    public String buscarPorTipoEnBD(int ID, int tipo){
        ControladorBD buscador = new ControladorBD();
        String [] tiposCampo = {"NUMERO", "BINARIO", "FECHAHORA", "TEXTO", "INCREMENTAL", "JERARQUIA", "LISTA"};
        String valores = "";
        try {
            ResultSet resultado = buscador.getResultSet("select * from " + tiposCampo[tipo-1] + " where correlativo = '" + Integer.toString(ID) + "';");
            if(resultado.next()){
                for(int i = 1; i<=resultado.getMetaData().getColumnCount(); ++i){
                    valores += resultado.getObject(i)!=null?resultado.getObject(i).toString() + ";":";";
                }
            }
        } catch (SQLException e) {
            System.out.println("*SQL Exception: *" + e.toString());
        }
        return valores;
    }

    /**
     * Encargado de buscar el valor del nombre en la base de datos
     * @param ID: Indica el ID del campo que va a buscar
     * @param tipo: Indica el tipo de campo que va a buscar
     */
    public String buscarMiembroLista(int ID){
        ControladorBD buscador = new ControladorBD();
        String valores = "";
        try {
            ResultSet resultado = buscador.getResultSet("select valor from MIEMBROLISTA where correlativo = " + ID + ";");
            if(resultado.next()){
                valores += resultado.getObject("valor").toString();
            }
        } catch (SQLException e) {
            System.out.println("*SQL Exception: *" + e.toString());
        }
        return valores;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameFormulario().setVisible(true);
            }
        });
    }

    @Action
    public void moverAlPrimero() {
    }

    @Action
    public void moverArriba() {
    }

    @Action
    public void moverAbajo() {
    }

    @Action
    public void moverAlUltimo() {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolPrincipal;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton bottonColor;
    private javax.swing.JTextField colorDato;
    private javax.swing.JComboBox comboCategorias;
    private javax.swing.JComboBox comboFormatoFecha;
    private javax.swing.JComboBox comboNiveles;
    private javax.swing.JComboBox comboTipoLetra;
    private javax.swing.JComboBox comboTipos;
    private javax.swing.JInternalFrame frameVistaPrevia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelCategorias;
    private javax.swing.JLayeredPane paneBinario;
    private javax.swing.JLayeredPane paneDatos;
    private javax.swing.JLayeredPane paneFechaHora;
    private javax.swing.JLayeredPane paneFormulario;
    private javax.swing.JLayeredPane paneIncremental;
    private javax.swing.JLayeredPane paneJerarquia;
    private javax.swing.JLayeredPane paneLista;
    private javax.swing.JLayeredPane paneNumero;
    private javax.swing.JLayeredPane panePrincipal;
    private javax.swing.JLayeredPane paneTexto;
    private javax.swing.JRadioButton radioCategoriasNo;
    private javax.swing.JRadioButton radioCategoriasSi;
    private javax.swing.JRadioButton radioFechaHoraNo;
    private javax.swing.JRadioButton radioFechaHoraSi;
    private javax.swing.JRadioButton radioNivelesNo;
    private javax.swing.JRadioButton radioNivelesSi;
    private javax.swing.JRadioButton radioNomUnicoNo;
    private javax.swing.JRadioButton radioNomUnicoSi;
    private javax.swing.JRadioButton radioOpcionBinaria1;
    private javax.swing.JRadioButton radioOpcionBinaria2;
    private javax.swing.JTextField tamanoLetra;
    private javax.swing.JTextField valEjeX;
    private javax.swing.JTextField valEjeY;
    private javax.swing.JTextField valorDato;
    private javax.swing.JFormattedTextField valorFechaDefecto;
    private javax.swing.JTextField valorIncremento;
    private javax.swing.JTextField valorNombreBinario1;
    private javax.swing.JTextField valorNombreBinario2;
    private javax.swing.JTextField valorNombreGeneral;
    private javax.swing.JTextField valorNota;
    private javax.swing.JTextField valorNumDecimales;
    private javax.swing.JTextField valorNumNiveles;
    private javax.swing.JTextField valorNumTerminos;
    private javax.swing.JTextField valorNumeroMascara;
    private javax.swing.JTextField valorOpcionBinaria1;
    private javax.swing.JTextField valorOpcionBinaria2;
    private javax.swing.JTextField valorPorDefectoLista;
    private javax.swing.JTextField valorPreaviso;
    private javax.swing.JTextField valorTextoDefecto;
    private javax.swing.JTextField valorTextoLargo;
    private javax.swing.JTextField valorValorDefectoNumero;
    private javax.swing.JTextField valorValorInicial;
    // End of variables declaration//GEN-END:variables
    public MouseListener listener;
    public MouseMotionListener motionListener;
    public float maxX;
    public float maxY;
    public float startX;
    public float startY;
    public Formulario miFormulario;
    public int IDEnUso;
}
